//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the ApplicationData datasource.
    /// </summary>
    public sealed partial class ApplicationDataService
        : global::LightSwitchApplication.ApplicationData
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ApplicationDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patrons_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patrons_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patrons_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patrons_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patrons_Inserting(global::LightSwitchApplication.Patron entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patrons_Inserted(global::LightSwitchApplication.Patron entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patrons_Updating(global::LightSwitchApplication.Patron entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patrons_Updated(global::LightSwitchApplication.Patron entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patrons_Deleting(global::LightSwitchApplication.Patron entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patrons_Deleted(global::LightSwitchApplication.Patron entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patrons_Validate(global::LightSwitchApplication.Patron entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patrons_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Patron, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Books_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Books_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Books_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Books_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Books_Inserting(global::LightSwitchApplication.Book entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Books_Inserted(global::LightSwitchApplication.Book entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Books_Updating(global::LightSwitchApplication.Book entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Books_Updated(global::LightSwitchApplication.Book entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Books_Deleting(global::LightSwitchApplication.Book entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Books_Deleted(global::LightSwitchApplication.Book entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Books_Validate(global::LightSwitchApplication.Book entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Books_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Book, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fees_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fees_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fees_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fees_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fees_Inserting(global::LightSwitchApplication.Fee entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fees_Inserted(global::LightSwitchApplication.Fee entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fees_Updating(global::LightSwitchApplication.Fee entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fees_Updated(global::LightSwitchApplication.Fee entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fees_Deleting(global::LightSwitchApplication.Fee entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fees_Deleted(global::LightSwitchApplication.Fee entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fees_Validate(global::LightSwitchApplication.Fee entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fees_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Fee, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CheckOuts_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CheckOuts_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CheckOuts_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CheckOuts_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CheckOuts_Inserting(global::LightSwitchApplication.CheckOut entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CheckOuts_Inserted(global::LightSwitchApplication.CheckOut entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CheckOuts_Updating(global::LightSwitchApplication.CheckOut entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CheckOuts_Updated(global::LightSwitchApplication.CheckOut entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CheckOuts_Deleting(global::LightSwitchApplication.CheckOut entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CheckOuts_Deleted(global::LightSwitchApplication.CheckOut entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CheckOuts_Validate(global::LightSwitchApplication.CheckOut entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CheckOuts_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.CheckOut, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BookSearchQuery_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void BookSearchQuery_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BookSearchQuery_PreprocessQuery(ref global::System.Linq.IQueryable<global::LightSwitchApplication.Book> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void BookSearchQuery_Executed(global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Book> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void BookSearchQuery_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ApplicationData_InitializingConnection(global::Microsoft.LightSwitch.DatabaseConnectionState state);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline")]
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Patron>
                __PatronsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Patron>(
                    "Patrons",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patrons_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patrons_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patrons_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patrons_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patrons_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patrons_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patrons_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patrons_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patrons_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patrons_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patrons_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patrons_Filter);
            private static bool __Patrons_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Patrons_CanInsert(ref result);
                return result;
            }
            private static bool __Patrons_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Patrons_CanUpdate(ref result);
                return result;
            }
            private static bool __Patrons_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Patrons_CanDelete(ref result);
                return result;
            }
            private static bool __Patrons_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Patrons_CanRead(ref result);
                return result;
            }
            private static void __Patrons_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Patron e)
            {
                d.Patrons_Inserting(e);
            }
            private static void __Patrons_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Patron e)
            {
                d.Patrons_Inserted(e);
            }
            private static void __Patrons_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Patron e)
            {
                d.Patrons_Updating(e);
            }
            private static void __Patrons_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Patron e)
            {
                d.Patrons_Updated(e);
            }
            private static void __Patrons_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Patron e)
            {
                d.Patrons_Deleting(e);
            }
            private static void __Patrons_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Patron e)
            {
                d.Patrons_Deleted(e);
            }
            private static void __Patrons_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Patron e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Patrons_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Patron, bool>> __Patrons_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Patron, bool>> filter = null;
                d.Patrons_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Book>
                __BooksEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Book>(
                    "Books",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Books_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Books_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Books_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Books_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Books_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Books_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Books_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Books_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Books_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Books_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Books_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Books_Filter);
            private static bool __Books_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Books_CanInsert(ref result);
                return result;
            }
            private static bool __Books_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Books_CanUpdate(ref result);
                return result;
            }
            private static bool __Books_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Books_CanDelete(ref result);
                return result;
            }
            private static bool __Books_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Books_CanRead(ref result);
                return result;
            }
            private static void __Books_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Book e)
            {
                d.Books_Inserting(e);
            }
            private static void __Books_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Book e)
            {
                d.Books_Inserted(e);
            }
            private static void __Books_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Book e)
            {
                d.Books_Updating(e);
            }
            private static void __Books_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Book e)
            {
                d.Books_Updated(e);
            }
            private static void __Books_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Book e)
            {
                d.Books_Deleting(e);
            }
            private static void __Books_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Book e)
            {
                d.Books_Deleted(e);
            }
            private static void __Books_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Book e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Books_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Book, bool>> __Books_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Book, bool>> filter = null;
                d.Books_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Fee>
                __FeesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Fee>(
                    "Fees",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Fees_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Fees_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Fees_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Fees_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Fees_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Fees_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Fees_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Fees_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Fees_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Fees_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Fees_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Fees_Filter);
            private static bool __Fees_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Fees_CanInsert(ref result);
                return result;
            }
            private static bool __Fees_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Fees_CanUpdate(ref result);
                return result;
            }
            private static bool __Fees_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Fees_CanDelete(ref result);
                return result;
            }
            private static bool __Fees_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Fees_CanRead(ref result);
                return result;
            }
            private static void __Fees_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Fee e)
            {
                d.Fees_Inserting(e);
            }
            private static void __Fees_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Fee e)
            {
                d.Fees_Inserted(e);
            }
            private static void __Fees_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Fee e)
            {
                d.Fees_Updating(e);
            }
            private static void __Fees_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Fee e)
            {
                d.Fees_Updated(e);
            }
            private static void __Fees_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Fee e)
            {
                d.Fees_Deleting(e);
            }
            private static void __Fees_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Fee e)
            {
                d.Fees_Deleted(e);
            }
            private static void __Fees_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Fee e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Fees_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Fee, bool>> __Fees_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Fee, bool>> filter = null;
                d.Fees_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.CheckOut>
                __CheckOutsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.CheckOut>(
                    "CheckOuts",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__CheckOuts_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__CheckOuts_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__CheckOuts_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__CheckOuts_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__CheckOuts_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__CheckOuts_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__CheckOuts_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__CheckOuts_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__CheckOuts_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__CheckOuts_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__CheckOuts_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__CheckOuts_Filter);
            private static bool __CheckOuts_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.CheckOuts_CanInsert(ref result);
                return result;
            }
            private static bool __CheckOuts_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.CheckOuts_CanUpdate(ref result);
                return result;
            }
            private static bool __CheckOuts_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.CheckOuts_CanDelete(ref result);
                return result;
            }
            private static bool __CheckOuts_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.CheckOuts_CanRead(ref result);
                return result;
            }
            private static void __CheckOuts_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.CheckOut e)
            {
                d.CheckOuts_Inserting(e);
            }
            private static void __CheckOuts_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.CheckOut e)
            {
                d.CheckOuts_Inserted(e);
            }
            private static void __CheckOuts_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.CheckOut e)
            {
                d.CheckOuts_Updating(e);
            }
            private static void __CheckOuts_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.CheckOut e)
            {
                d.CheckOuts_Updated(e);
            }
            private static void __CheckOuts_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.CheckOut e)
            {
                d.CheckOuts_Deleting(e);
            }
            private static void __CheckOuts_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.CheckOut e)
            {
                d.CheckOuts_Deleted(e);
            }
            private static void __CheckOuts_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.CheckOut e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.CheckOuts_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.CheckOut, bool>> __CheckOuts_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.CheckOut, bool>> filter = null;
                d.CheckOuts_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>(
                    "SaveChanges",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Book>
                __BookSearchQueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Book>(
                    "BookSearchQuery",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__BookSearchQuery_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__BookSearchQuery_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__BookSearchQuery_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__BookSearchQuery_Failed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__BookSearchQuery_PreprocessQuery);
            private static bool __BookSearchQuery_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.BookSearchQuery_CanExecute(ref r);
                return r;
            }
            private static void __BookSearchQuery_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.BookSearchQuery_Executing();
            }
            private static void __BookSearchQuery_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.BookSearchQuery_Executed((global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Book>)args[0]);
            }
            private static void __BookSearchQuery_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.BookSearchQuery_ExecuteFailed(ex);
            }
            private static global::System.Linq.IQueryable __BookSearchQuery_PreprocessQuery(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.Book> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.Book>)args[0];
                d.BookSearchQuery_PreprocessQuery(ref query);
                return query;
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>(
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.DatabaseAuthEntry<global::LightSwitchApplication.ApplicationDataService>
                ___DatabaseAuthEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.DatabaseAuthEntry<global::LightSwitchApplication.ApplicationDataService>(
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ApplicationData_InitializingConnection);
            private static void __ApplicationData_InitializingConnection(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.DatabaseConnectionState state)
            {
                d.ApplicationData_InitializingConnection(state);
            }
        }
    
        #endregion
    }
    
    #endregion
}
