//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region Patron
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Patron :
        global::LightSwitchApplication.Patron.DetailsClass.IImplementation
    {
        partial void OnPatron_BookChanged()
        {
            this.___OnPropertyChanged("Patron_Book");
            this.___OnPropertyChanged("Book");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnLastNameChanged()
        {
            this.___OnPropertyChanged("LastName");
        }
        
        partial void OnFirstNameChanged()
        {
            this.___OnPropertyChanged("FirstName");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnPhoneChanged()
        {
            this.___OnPropertyChanged("Phone");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Patron.DetailsClass.IImplementation.Book
        {
            get
            {
                return this.Book;
            }
            set
            {
                this.Book = (global::LightSwitchApplication.Implementation.Book)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Book> __Book
        {
            get
            {
                if (this.___Book == null)
                {
                    this.___Book = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Book>(
                        this,
                        "Book",
                        new string[] { "Patron_Book" },
                        e => global::System.Object.Equals(e.Id, this.Patron_Book),
                        () => this._Book,
                        e => this._Book = e);
                }
                return this.___Book;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Book> ___Book;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Patron.DetailsClass.IImplementation.Fees
        {
            get
            {
                return this.Fees;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Fee> __Fees
        {
            get
            {
                if (this.___Fees == null)
                {
                    this.___Fees = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Fee>(
                        this,
                        "Fees",
                        () => this._Fees,
                        e => global::System.Object.Equals(e.Patron_Fee, this.Id));
                }
                return this.___Fees;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Fee> ___Fees;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Patron.DetailsClass.IImplementation.CheckOuts
        {
            get
            {
                return this.CheckOuts;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CheckOut> __CheckOuts
        {
            get
            {
                if (this.___CheckOuts == null)
                {
                    this.___CheckOuts = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CheckOut>(
                        this,
                        "CheckOuts",
                        () => this._CheckOuts,
                        e => global::System.Object.Equals(e.CheckOut_Patron, this.Id));
                }
                return this.___CheckOuts;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CheckOut> ___CheckOuts;
        
    }
    #endregion
    
    #region Book
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Book :
        global::LightSwitchApplication.Book.DetailsClass.IImplementation
    {
        partial void OnCheckOut_BookChanged()
        {
            this.___OnPropertyChanged("CheckOut_Book");
            this.___OnPropertyChanged("CheckOut");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCoverChanged()
        {
            this.___OnPropertyChanged("Cover");
        }
        
        partial void OnTitleChanged()
        {
            this.___OnPropertyChanged("Title");
        }
        
        partial void OnAuthorChanged()
        {
            this.___OnPropertyChanged("Author");
        }
        
        partial void OnSeriesChanged()
        {
            this.___OnPropertyChanged("Series");
        }
        
        partial void OnBookNumberChanged()
        {
            this.___OnPropertyChanged("BookNumber");
        }
        
        partial void OnDescriptionChanged()
        {
            this.___OnPropertyChanged("Description");
        }
        
        partial void OnISBNChanged()
        {
            this.___OnPropertyChanged("ISBN");
        }
        
        partial void OnPublisherChanged()
        {
            this.___OnPropertyChanged("Publisher");
        }
        
        partial void OnPublishDateChanged()
        {
            this.___OnPropertyChanged("PublishDate");
        }
        
        partial void OnPagesChanged()
        {
            this.___OnPropertyChanged("Pages");
        }
        
        partial void OnQuantityChanged()
        {
            this.___OnPropertyChanged("Quantity");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Book.DetailsClass.IImplementation.Patrons
        {
            get
            {
                return this.Patrons;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Patron> __Patrons
        {
            get
            {
                if (this.___Patrons == null)
                {
                    this.___Patrons = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Patron>(
                        this,
                        "Patrons",
                        () => this._Patrons,
                        e => global::System.Object.Equals(e.Patron_Book, this.Id));
                }
                return this.___Patrons;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Patron> ___Patrons;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Book.DetailsClass.IImplementation.CheckOut
        {
            get
            {
                return this.CheckOut;
            }
            set
            {
                this.CheckOut = (global::LightSwitchApplication.Implementation.CheckOut)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.CheckOut> __CheckOut
        {
            get
            {
                if (this.___CheckOut == null)
                {
                    this.___CheckOut = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.CheckOut>(
                        this,
                        "CheckOut",
                        new string[] { "CheckOut_Book" },
                        e => global::System.Object.Equals(e.Id, this.CheckOut_Book),
                        () => this._CheckOut,
                        e => this._CheckOut = e);
                }
                return this.___CheckOut;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.CheckOut> ___CheckOut;
        
    }
    #endregion
    
    #region Fee
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Fee :
        global::LightSwitchApplication.Fee.DetailsClass.IImplementation
    {
        partial void OnPatron_FeeChanged()
        {
            this.___OnPropertyChanged("Patron_Fee");
            this.___OnPropertyChanged("Patron");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnReasonChanged()
        {
            this.___OnPropertyChanged("Reason");
        }
        
        partial void OnAmountChanged()
        {
            this.___OnPropertyChanged("Amount");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Fee.DetailsClass.IImplementation.Patron
        {
            get
            {
                return this.Patron;
            }
            set
            {
                this.Patron = (global::LightSwitchApplication.Implementation.Patron)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Patron> __Patron
        {
            get
            {
                if (this.___Patron == null)
                {
                    this.___Patron = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Patron>(
                        this,
                        "Patron",
                        new string[] { "Patron_Fee" },
                        e => global::System.Object.Equals(e.Id, this.Patron_Fee),
                        () => this._Patron,
                        e => this._Patron = e);
                }
                return this.___Patron;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Patron> ___Patron;
        
    }
    #endregion
    
    #region CheckOut
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class CheckOut :
        global::LightSwitchApplication.CheckOut.DetailsClass.IImplementation
    {
        partial void OnCheckOut_PatronChanged()
        {
            this.___OnPropertyChanged("CheckOut_Patron");
            this.___OnPropertyChanged("Patron");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.CheckOut.DetailsClass.IImplementation.Books
        {
            get
            {
                return this.Books;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Book> __Books
        {
            get
            {
                if (this.___Books == null)
                {
                    this.___Books = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Book>(
                        this,
                        "Books",
                        () => this._Books,
                        e => global::System.Object.Equals(e.CheckOut_Book, this.Id));
                }
                return this.___Books;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Book> ___Books;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.CheckOut.DetailsClass.IImplementation.Patron
        {
            get
            {
                return this.Patron;
            }
            set
            {
                this.Patron = (global::LightSwitchApplication.Implementation.Patron)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Patron> __Patron
        {
            get
            {
                if (this.___Patron == null)
                {
                    this.___Patron = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Patron>(
                        this,
                        "Patron",
                        new string[] { "CheckOut_Patron" },
                        e => global::System.Object.Equals(e.Id, this.CheckOut_Patron),
                        () => this._Patron,
                        e => this._Patron = e);
                }
                return this.___Patron;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Patron> ___Patron;
        
    }
    #endregion
    
    #region ApplicationData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Patron))
            {
                return new global::LightSwitchApplication.Implementation.Patron();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Book))
            {
                return new global::LightSwitchApplication.Implementation.Book();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Fee))
            {
                return new global::LightSwitchApplication.Implementation.Fee();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.CheckOut))
            {
                return new global::LightSwitchApplication.Implementation.CheckOut();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.ApplicationData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Patron) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Patron);
            }
            if (typeof(global::LightSwitchApplication.Book) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Book);
            }
            if (typeof(global::LightSwitchApplication.Fee) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Fee);
            }
            if (typeof(global::LightSwitchApplication.CheckOut) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.CheckOut);
            }
            return null;
        }
    }
}
