//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class BookDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private BookDetail(int BookId) : base("LightSwitchApplication.LibraryManagement.DesktopClient:BookDetail")
        {
                this.BookId = BookId;
            global::LightSwitchApplication.BookDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static BookDetail CreateInstance(int BookId)
        {
            return new global::LightSwitchApplication.BookDetail(
                        BookId
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BookDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BookDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BookDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BookDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BookDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BookDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BookDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Book_Changed();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Book_Loaded(bool succeeded);

        partial void BookId_Changed();

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Book Book
        {
            get
            {
                return global::LightSwitchApplication.BookDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.BookDetail.DetailsClass.PropertySetProperties.Book);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Book_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int BookId
        {
            get 
            {
                return global::LightSwitchApplication.BookDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.BookDetail.DetailsClass.PropertySetProperties.BookId);
            }
            set
            {
                global::LightSwitchApplication.BookDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.BookDetail.DetailsClass.PropertySetProperties.BookId, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BookId_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Calls the Method screen method.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Method()
        {
            this.Details.Methods.Method.CreateInvocation().Execute();
        }
        partial void Method_CanExecute(ref bool result);
        partial void Method_Execute();

        /// <summary>
        /// Calls the Method1 screen method.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Method1()
        {
            this.Details.Methods.Method1.CreateInvocation().Execute();
        }
        partial void Method1_CanExecute(ref bool result);
        partial void Method1_Execute();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass, global::LightSwitchApplication.BookDetail.DetailsClass.PropertySet, global::LightSwitchApplication.BookDetail.DetailsClass.CommandSet, global::LightSwitchApplication.BookDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.BookDetail.DetailsClass.PropertySetProperties.Book;
                var initializeCommandEntry = global::LightSwitchApplication.BookDetail.DetailsClass.CommandSetProperties.Method;
                var initializeMethodEntry = global::LightSwitchApplication.BookDetail.DetailsClass.MethodSetProperties.Method;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>.Entry
                __BookDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.BookDetail.DetailsClass.__BookDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.BookDetail.DetailsClass.__BookDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.BookDetail.DetailsClass.__BookDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.BookDetail.DetailsClass.__BookDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.BookDetail.DetailsClass.__BookDetail_InvokeCreated,
                    global::LightSwitchApplication.BookDetail.DetailsClass.__BookDetail_InvokeActivated,
                    global::LightSwitchApplication.BookDetail.DetailsClass.__BookDetail_InvokeSaveErrorEvent);
            private static void __BookDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.BookDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.BookDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __BookDetail_InvokeSavingEvent(global::LightSwitchApplication.BookDetail s)
            {
                bool handled = false;
                s.BookDetail_Saving(ref handled);
                return handled;
            }
            private static void __BookDetail_InvokeSavedEvent(global::LightSwitchApplication.BookDetail s)
            {
                s.BookDetail_Saved();
            }
            private static bool __BookDetail_InvokeClosingEvent(global::LightSwitchApplication.BookDetail s)
            {
                bool cancel = false;
                s.BookDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __BookDetail_InvokeCreated(global::LightSwitchApplication.BookDetail s)
            {
                s.BookDetail_Created();
            }
            private static void __BookDetail_InvokeActivated(global::LightSwitchApplication.BookDetail s)
            {
                s.BookDetail_Activated();
            }
            private static bool __BookDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.BookDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.BookDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.BookDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.BookDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.BookDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass, global::LightSwitchApplication.Book>.Data _Book;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass, int>.Data _BookId;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>.Data _MethodCommand;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>.Data _Method1Command;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>.Data _MethodMethod;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>.Data _Method1Method;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass, global::LightSwitchApplication.Book> Book
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass, global::LightSwitchApplication.Book>)base.GetItem(global::LightSwitchApplication.BookDetail.DetailsClass.PropertySetProperties.Book);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass, int> BookId
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass, int>)base.GetItem(global::LightSwitchApplication.BookDetail.DetailsClass.PropertySetProperties.BookId);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass> Method
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>)base.GetItem(global::LightSwitchApplication.BookDetail.DetailsClass.CommandSetProperties.Method);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass> Method1
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>)base.GetItem(global::LightSwitchApplication.BookDetail.DetailsClass.CommandSetProperties.Method1);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass> Method
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>)base.GetItem(global::LightSwitchApplication.BookDetail.DetailsClass.MethodSetProperties.Method);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass> Method1
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>)base.GetItem(global::LightSwitchApplication.BookDetail.DetailsClass.MethodSetProperties.Method1);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass, global::LightSwitchApplication.Book>.Entry
                    Book = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass, global::LightSwitchApplication.Book>.Entry(
                        "Book",
                        global::LightSwitchApplication.BookDetail.DetailsClass.PropertySetProperties._Book_Stub,
                        global::LightSwitchApplication.BookDetail.DetailsClass.PropertySetProperties._Book_Validate,
                        global::LightSwitchApplication.BookDetail.DetailsClass.PropertySetProperties._Book_CreateQuery,
                        global::LightSwitchApplication.BookDetail.DetailsClass.PropertySetProperties._Book_OnValueChanged,
                        global::LightSwitchApplication.BookDetail.DetailsClass.PropertySetProperties._Book_OnLoaded);
                private static void _Book_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BookDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass, global::LightSwitchApplication.Book>.Data> c, global::LightSwitchApplication.BookDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Book, sf);
                }
                private static void _Book_Validate(global::LightSwitchApplication.BookDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Book_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Book_CreateQuery(global::LightSwitchApplication.BookDetail.DetailsClass d, object[] args)
                {
                    return null;
                }
                private static void _Book_OnValueChanged(global::LightSwitchApplication.BookDetail s)
                {
                    s.Book_Changed();
                }

                private static void _Book_OnLoaded(global::LightSwitchApplication.BookDetail s, bool succeeded)
                {
                    s.Book_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass, int>.Entry
                    BookId = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass, int>.Entry(
                        "BookId",
                        false,
                        global::LightSwitchApplication.BookDetail.DetailsClass.PropertySetProperties._BookId_Stub,
                        global::LightSwitchApplication.BookDetail.DetailsClass.PropertySetProperties._BookId_Validate,
                        global::LightSwitchApplication.BookDetail.DetailsClass.PropertySetProperties._BookId_OnValueChanged);
                private static void _BookId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BookDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass, int>.Data> c, global::LightSwitchApplication.BookDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._BookId, sf);
                }
                private static void _BookId_Validate(global::LightSwitchApplication.BookDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.BookId_Validate(r);
                }
                private static void _BookId_OnValueChanged(global::LightSwitchApplication.BookDetail s)
                {
                    s.BookId_Changed();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>.Entry
                    Method = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>.Entry(
                        "Method",
                        global::LightSwitchApplication.BookDetail.DetailsClass.CommandSetProperties._Method_Stub,
                        global::LightSwitchApplication.BookDetail.DetailsClass.CommandSetProperties._Method_CreateExecutableObject);
                private static void _Method_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BookDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>.Data> c, global::LightSwitchApplication.BookDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._MethodCommand, sf);
                }
                private static global::Microsoft.LightSwitch.IExecutable _Method_CreateExecutableObject(global::LightSwitchApplication.BookDetail.DetailsClass d)
                {
                    return ((global::LightSwitchApplication.BookDetail.DetailsClass)d).Methods.Method.CreateInvocation();
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>.Entry
                    Method1 = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>.Entry(
                        "Method1",
                        global::LightSwitchApplication.BookDetail.DetailsClass.CommandSetProperties._Method1_Stub,
                        global::LightSwitchApplication.BookDetail.DetailsClass.CommandSetProperties._Method1_CreateExecutableObject);
                private static void _Method1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BookDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>.Data> c, global::LightSwitchApplication.BookDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Method1Command, sf);
                }
                private static global::Microsoft.LightSwitch.IExecutable _Method1_CreateExecutableObject(global::LightSwitchApplication.BookDetail.DetailsClass d)
                {
                    return ((global::LightSwitchApplication.BookDetail.DetailsClass)d).Methods.Method1.CreateInvocation();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>.Entry
                    Method = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>.Entry(
                        "Method",
                        global::LightSwitchApplication.BookDetail.DetailsClass.MethodSetProperties._Method_Stub,
                        global::LightSwitchApplication.BookDetail.DetailsClass.MethodSetProperties._Method_CanInvoke,
                        global::LightSwitchApplication.BookDetail.DetailsClass.MethodSetProperties._Method_InvokeMethod);
                private static void _Method_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BookDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>.Data> c, global::LightSwitchApplication.BookDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._MethodMethod, sf);
                }
                private static global::System.Exception _Method_CanInvoke(global::LightSwitchApplication.BookDetail.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args, global::System.Exception ex)
                {
                    bool result = true;
                    d.Screen.Method_CanExecute(ref result);
                    return result ? null : ex;
                }
                private static void _Method_InvokeMethod(global::LightSwitchApplication.BookDetail.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args)
                {
                    d.Screen.Method_Execute();
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>.Entry
                    Method1 = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>.Entry(
                        "Method1",
                        global::LightSwitchApplication.BookDetail.DetailsClass.MethodSetProperties._Method1_Stub,
                        global::LightSwitchApplication.BookDetail.DetailsClass.MethodSetProperties._Method1_CanInvoke,
                        global::LightSwitchApplication.BookDetail.DetailsClass.MethodSetProperties._Method1_InvokeMethod);
                private static void _Method1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BookDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.BookDetail, global::LightSwitchApplication.BookDetail.DetailsClass>.Data> c, global::LightSwitchApplication.BookDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Method1Method, sf);
                }
                private static global::System.Exception _Method1_CanInvoke(global::LightSwitchApplication.BookDetail.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args, global::System.Exception ex)
                {
                    bool result = true;
                    d.Screen.Method1_CanExecute(ref result);
                    return result ? null : ex;
                }
                private static void _Method1_InvokeMethod(global::LightSwitchApplication.BookDetail.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args)
                {
                    d.Screen.Method1_Execute();
                }

            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class SearchBooks
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private SearchBooks() : base("LightSwitchApplication.LibraryManagement.DesktopClient:SearchBooks")
        {
            global::LightSwitchApplication.SearchBooks.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static SearchBooks CreateInstance()
        {
            return new global::LightSwitchApplication.SearchBooks(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchBooks_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchBooks_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchBooks_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchBooks_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchBooks_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchBooks_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchBooks_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Books_SelectionChanged();

        partial void Books_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Books_Loaded(bool succeeded);

        partial void BookSearchQuery_SelectionChanged();

        partial void BookSearchQuery_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BookSearchQuery_Loaded(bool succeeded);

        /// <summary>
        /// Gets the Books visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Book> Books
        {
            get
            {
                return global::LightSwitchApplication.SearchBooks.DetailsClass.GetValue(this, global::LightSwitchApplication.SearchBooks.DetailsClass.PropertySetProperties.Books);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Books_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the BookSearchQuery visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Book> BookSearchQuery
        {
            get
            {
                return global::LightSwitchApplication.SearchBooks.DetailsClass.GetValue(this, global::LightSwitchApplication.SearchBooks.DetailsClass.PropertySetProperties.BookSearchQuery);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BookSearchQuery_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Calls the Method screen method.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Method()
        {
            this.Details.Methods.Method.CreateInvocation().Execute();
        }
        partial void Method_CanExecute(ref bool result);
        partial void Method_Execute();

        /// <summary>
        /// Calls the AddtoCart screen method.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void AddtoCart()
        {
            this.Details.Methods.AddtoCart.CreateInvocation().Execute();
        }
        partial void AddtoCart_CanExecute(ref bool result);
        partial void AddtoCart_Execute();

        /// <summary>
        /// Calls the RemoveFromCart screen method.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void RemoveFromCart()
        {
            this.Details.Methods.RemoveFromCart.CreateInvocation().Execute();
        }
        partial void RemoveFromCart_CanExecute(ref bool result);
        partial void RemoveFromCart_Execute();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass, global::LightSwitchApplication.SearchBooks.DetailsClass.PropertySet, global::LightSwitchApplication.SearchBooks.DetailsClass.CommandSet, global::LightSwitchApplication.SearchBooks.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.SearchBooks.DetailsClass.PropertySetProperties.Books;
                var initializeCommandEntry = global::LightSwitchApplication.SearchBooks.DetailsClass.CommandSetProperties.Method;
                var initializeMethodEntry = global::LightSwitchApplication.SearchBooks.DetailsClass.MethodSetProperties.Method;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Entry
                __SearchBooksEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Entry(
                    global::LightSwitchApplication.SearchBooks.DetailsClass.__SearchBooks_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.SearchBooks.DetailsClass.__SearchBooks_InvokeSavingEvent,
                    global::LightSwitchApplication.SearchBooks.DetailsClass.__SearchBooks_InvokeSavedEvent,
                    global::LightSwitchApplication.SearchBooks.DetailsClass.__SearchBooks_InvokeClosingEvent,
                    global::LightSwitchApplication.SearchBooks.DetailsClass.__SearchBooks_InvokeCreated,
                    global::LightSwitchApplication.SearchBooks.DetailsClass.__SearchBooks_InvokeActivated,
                    global::LightSwitchApplication.SearchBooks.DetailsClass.__SearchBooks_InvokeSaveErrorEvent);
            private static void __SearchBooks_InvokeInitializeDataWorkspace(global::LightSwitchApplication.SearchBooks s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.SearchBooks_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __SearchBooks_InvokeSavingEvent(global::LightSwitchApplication.SearchBooks s)
            {
                bool handled = false;
                s.SearchBooks_Saving(ref handled);
                return handled;
            }
            private static void __SearchBooks_InvokeSavedEvent(global::LightSwitchApplication.SearchBooks s)
            {
                s.SearchBooks_Saved();
            }
            private static bool __SearchBooks_InvokeClosingEvent(global::LightSwitchApplication.SearchBooks s)
            {
                bool cancel = false;
                s.SearchBooks_Closing(ref cancel);
                return cancel;
            }
            private static void __SearchBooks_InvokeCreated(global::LightSwitchApplication.SearchBooks s)
            {
                s.SearchBooks_Created();
            }
            private static void __SearchBooks_InvokeActivated(global::LightSwitchApplication.SearchBooks s)
            {
                s.SearchBooks_Activated();
            }
            private static bool __SearchBooks_InvokeSaveErrorEvent(global::LightSwitchApplication.SearchBooks s, global::System.Exception ex)
            {
                bool handled = false;
                s.SearchBooks_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.SearchBooks.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.SearchBooks.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.SearchBooks.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable BooksQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.Books;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable BookSearchQueryQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.BookSearchQuery();
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass, global::LightSwitchApplication.Book>.Data _Books;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass, global::LightSwitchApplication.Book>.Data _BookSearchQuery;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Data _MethodCommand;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Data _AddtoCartCommand;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Data _RemoveFromCartCommand;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Data _MethodMethod;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Data _AddtoCartMethod;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Data _RemoveFromCartMethod;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass, global::LightSwitchApplication.Book> Books
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass, global::LightSwitchApplication.Book>)base.GetItem(global::LightSwitchApplication.SearchBooks.DetailsClass.PropertySetProperties.Books);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass, global::LightSwitchApplication.Book> BookSearchQuery
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass, global::LightSwitchApplication.Book>)base.GetItem(global::LightSwitchApplication.SearchBooks.DetailsClass.PropertySetProperties.BookSearchQuery);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass> Method
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>)base.GetItem(global::LightSwitchApplication.SearchBooks.DetailsClass.CommandSetProperties.Method);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass> AddtoCart
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>)base.GetItem(global::LightSwitchApplication.SearchBooks.DetailsClass.CommandSetProperties.AddtoCart);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass> RemoveFromCart
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>)base.GetItem(global::LightSwitchApplication.SearchBooks.DetailsClass.CommandSetProperties.RemoveFromCart);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass> Method
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>)base.GetItem(global::LightSwitchApplication.SearchBooks.DetailsClass.MethodSetProperties.Method);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass> AddtoCart
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>)base.GetItem(global::LightSwitchApplication.SearchBooks.DetailsClass.MethodSetProperties.AddtoCart);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass> RemoveFromCart
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>)base.GetItem(global::LightSwitchApplication.SearchBooks.DetailsClass.MethodSetProperties.RemoveFromCart);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass, global::LightSwitchApplication.Book>.Entry
                    Books = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass, global::LightSwitchApplication.Book>.Entry(
                        "Books",
                        global::LightSwitchApplication.SearchBooks.DetailsClass.PropertySetProperties._Books_Stub,
                        global::LightSwitchApplication.SearchBooks.DetailsClass.PropertySetProperties._Books_Validate,
                        global::LightSwitchApplication.SearchBooks.DetailsClass.PropertySetProperties._Books_CreateQuery,
                        global::LightSwitchApplication.SearchBooks.DetailsClass.PropertySetProperties._Books_SelectionChanged,
                        global::LightSwitchApplication.SearchBooks.DetailsClass.PropertySetProperties._Books_OnCollectionChanged,
                        global::LightSwitchApplication.SearchBooks.DetailsClass.PropertySetProperties._Books_OnLoaded);
                private static void _Books_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SearchBooks.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass, global::LightSwitchApplication.Book>.Data> c, global::LightSwitchApplication.SearchBooks.DetailsClass d, object sf)
                {
                    c(d, ref d._Books, sf);
                }
                private static void _Books_Validate(global::LightSwitchApplication.SearchBooks s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Books_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Books_CreateQuery(global::LightSwitchApplication.SearchBooks.DetailsClass d, object[] args)
                {
                    return d.BooksQuery();
                }
                private static void _Books_SelectionChanged(global::LightSwitchApplication.SearchBooks s)
                {
                    s.Books_SelectionChanged();
                }
                private static void _Books_OnCollectionChanged(global::LightSwitchApplication.SearchBooks s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Books_Changed(e);
                }
                private static void _Books_OnLoaded(global::LightSwitchApplication.SearchBooks s, bool succeeded)
                {
                    s.Books_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass, global::LightSwitchApplication.Book>.Entry
                    BookSearchQuery = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass, global::LightSwitchApplication.Book>.Entry(
                        "BookSearchQuery",
                        global::LightSwitchApplication.SearchBooks.DetailsClass.PropertySetProperties._BookSearchQuery_Stub,
                        global::LightSwitchApplication.SearchBooks.DetailsClass.PropertySetProperties._BookSearchQuery_Validate,
                        global::LightSwitchApplication.SearchBooks.DetailsClass.PropertySetProperties._BookSearchQuery_CreateQuery,
                        global::LightSwitchApplication.SearchBooks.DetailsClass.PropertySetProperties._BookSearchQuery_SelectionChanged,
                        global::LightSwitchApplication.SearchBooks.DetailsClass.PropertySetProperties._BookSearchQuery_OnCollectionChanged,
                        global::LightSwitchApplication.SearchBooks.DetailsClass.PropertySetProperties._BookSearchQuery_OnLoaded);
                private static void _BookSearchQuery_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SearchBooks.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass, global::LightSwitchApplication.Book>.Data> c, global::LightSwitchApplication.SearchBooks.DetailsClass d, object sf)
                {
                    c(d, ref d._BookSearchQuery, sf);
                }
                private static void _BookSearchQuery_Validate(global::LightSwitchApplication.SearchBooks s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.BookSearchQuery_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _BookSearchQuery_CreateQuery(global::LightSwitchApplication.SearchBooks.DetailsClass d, object[] args)
                {
                    return d.BookSearchQueryQuery();
                }
                private static void _BookSearchQuery_SelectionChanged(global::LightSwitchApplication.SearchBooks s)
                {
                    s.BookSearchQuery_SelectionChanged();
                }
                private static void _BookSearchQuery_OnCollectionChanged(global::LightSwitchApplication.SearchBooks s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.BookSearchQuery_Changed(e);
                }
                private static void _BookSearchQuery_OnLoaded(global::LightSwitchApplication.SearchBooks s, bool succeeded)
                {
                    s.BookSearchQuery_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Entry
                    Method = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Entry(
                        "Method",
                        global::LightSwitchApplication.SearchBooks.DetailsClass.CommandSetProperties._Method_Stub,
                        global::LightSwitchApplication.SearchBooks.DetailsClass.CommandSetProperties._Method_CreateExecutableObject);
                private static void _Method_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SearchBooks.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Data> c, global::LightSwitchApplication.SearchBooks.DetailsClass d, object sf)
                {
                    c(d, ref d._MethodCommand, sf);
                }
                private static global::Microsoft.LightSwitch.IExecutable _Method_CreateExecutableObject(global::LightSwitchApplication.SearchBooks.DetailsClass d)
                {
                    return ((global::LightSwitchApplication.SearchBooks.DetailsClass)d).Methods.Method.CreateInvocation();
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Entry
                    AddtoCart = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Entry(
                        "AddtoCart",
                        global::LightSwitchApplication.SearchBooks.DetailsClass.CommandSetProperties._AddtoCart_Stub,
                        global::LightSwitchApplication.SearchBooks.DetailsClass.CommandSetProperties._AddtoCart_CreateExecutableObject);
                private static void _AddtoCart_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SearchBooks.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Data> c, global::LightSwitchApplication.SearchBooks.DetailsClass d, object sf)
                {
                    c(d, ref d._AddtoCartCommand, sf);
                }
                private static global::Microsoft.LightSwitch.IExecutable _AddtoCart_CreateExecutableObject(global::LightSwitchApplication.SearchBooks.DetailsClass d)
                {
                    return ((global::LightSwitchApplication.SearchBooks.DetailsClass)d).Methods.AddtoCart.CreateInvocation();
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Entry
                    RemoveFromCart = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Entry(
                        "RemoveFromCart",
                        global::LightSwitchApplication.SearchBooks.DetailsClass.CommandSetProperties._RemoveFromCart_Stub,
                        global::LightSwitchApplication.SearchBooks.DetailsClass.CommandSetProperties._RemoveFromCart_CreateExecutableObject);
                private static void _RemoveFromCart_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SearchBooks.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Data> c, global::LightSwitchApplication.SearchBooks.DetailsClass d, object sf)
                {
                    c(d, ref d._RemoveFromCartCommand, sf);
                }
                private static global::Microsoft.LightSwitch.IExecutable _RemoveFromCart_CreateExecutableObject(global::LightSwitchApplication.SearchBooks.DetailsClass d)
                {
                    return ((global::LightSwitchApplication.SearchBooks.DetailsClass)d).Methods.RemoveFromCart.CreateInvocation();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Entry
                    Method = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Entry(
                        "Method",
                        global::LightSwitchApplication.SearchBooks.DetailsClass.MethodSetProperties._Method_Stub,
                        global::LightSwitchApplication.SearchBooks.DetailsClass.MethodSetProperties._Method_CanInvoke,
                        global::LightSwitchApplication.SearchBooks.DetailsClass.MethodSetProperties._Method_InvokeMethod);
                private static void _Method_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SearchBooks.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Data> c, global::LightSwitchApplication.SearchBooks.DetailsClass d, object sf)
                {
                    c(d, ref d._MethodMethod, sf);
                }
                private static global::System.Exception _Method_CanInvoke(global::LightSwitchApplication.SearchBooks.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args, global::System.Exception ex)
                {
                    bool result = true;
                    d.Screen.Method_CanExecute(ref result);
                    return result ? null : ex;
                }
                private static void _Method_InvokeMethod(global::LightSwitchApplication.SearchBooks.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args)
                {
                    d.Screen.Method_Execute();
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Entry
                    AddtoCart = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Entry(
                        "AddtoCart",
                        global::LightSwitchApplication.SearchBooks.DetailsClass.MethodSetProperties._AddtoCart_Stub,
                        global::LightSwitchApplication.SearchBooks.DetailsClass.MethodSetProperties._AddtoCart_CanInvoke,
                        global::LightSwitchApplication.SearchBooks.DetailsClass.MethodSetProperties._AddtoCart_InvokeMethod);
                private static void _AddtoCart_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SearchBooks.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Data> c, global::LightSwitchApplication.SearchBooks.DetailsClass d, object sf)
                {
                    c(d, ref d._AddtoCartMethod, sf);
                }
                private static global::System.Exception _AddtoCart_CanInvoke(global::LightSwitchApplication.SearchBooks.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args, global::System.Exception ex)
                {
                    bool result = true;
                    d.Screen.AddtoCart_CanExecute(ref result);
                    return result ? null : ex;
                }
                private static void _AddtoCart_InvokeMethod(global::LightSwitchApplication.SearchBooks.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args)
                {
                    d.Screen.AddtoCart_Execute();
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Entry
                    RemoveFromCart = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Entry(
                        "RemoveFromCart",
                        global::LightSwitchApplication.SearchBooks.DetailsClass.MethodSetProperties._RemoveFromCart_Stub,
                        global::LightSwitchApplication.SearchBooks.DetailsClass.MethodSetProperties._RemoveFromCart_CanInvoke,
                        global::LightSwitchApplication.SearchBooks.DetailsClass.MethodSetProperties._RemoveFromCart_InvokeMethod);
                private static void _RemoveFromCart_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SearchBooks.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchBooks, global::LightSwitchApplication.SearchBooks.DetailsClass>.Data> c, global::LightSwitchApplication.SearchBooks.DetailsClass d, object sf)
                {
                    c(d, ref d._RemoveFromCartMethod, sf);
                }
                private static global::System.Exception _RemoveFromCart_CanInvoke(global::LightSwitchApplication.SearchBooks.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args, global::System.Exception ex)
                {
                    bool result = true;
                    d.Screen.RemoveFromCart_CanExecute(ref result);
                    return result ? null : ex;
                }
                private static void _RemoveFromCart_InvokeMethod(global::LightSwitchApplication.SearchBooks.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args)
                {
                    d.Screen.RemoveFromCart_Execute();
                }

            }
        }
    }
}
